// <auto-generated />
using System;
using HomeAssistant.SmartPlugApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeAssistant.SmartPlugApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeAssistant.Common.Models.SmartDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DevicePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomIndex")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.ToTable("SmartDevices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HomeAssistant.SmartPlugApi.Models.Domain.SmartPlug", b =>
                {
                    b.HasBaseType("HomeAssistant.Common.Models.SmartDevice");

                    b.Property<float>("UsageKw")
                        .HasColumnType("real");

                    b.ToTable("SmartPlug", (string)null);
                });

            modelBuilder.Entity("HomeAssistant.SmartPlugApi.Models.Domain.SmartPlug", b =>
                {
                    b.HasOne("HomeAssistant.Common.Models.SmartDevice", null)
                        .WithOne()
                        .HasForeignKey("HomeAssistant.SmartPlugApi.Models.Domain.SmartPlug", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
