// <auto-generated />
using System;
using HomeAssistant.SmartWasherApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeAssistant.SmartWasherApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120102717_SmartWasher_InitialCreate")]
    partial class SmartWasher_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeAssistant.Common.Models.RoomIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("RoomsIndex", (string)null);
                });

            modelBuilder.Entity("HomeAssistant.Common.Models.SmartDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DevicePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.ToTable("SmartDevices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HomeAssistant.SmartWasherApi.Models.Domain.SmartWasher", b =>
                {
                    b.HasBaseType("HomeAssistant.Common.Models.SmartDevice");

                    b.Property<int>("SoilLevel")
                        .HasColumnType("int");

                    b.Property<int>("SpeedLevel")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("WashingMode")
                        .HasColumnType("int");

                    b.ToTable("SmartWasher", (string)null);
                });

            modelBuilder.Entity("HomeAssistant.Common.Models.RoomIndex", b =>
                {
                    b.HasOne("HomeAssistant.Common.Models.SmartDevice", "SmartDevice")
                        .WithMany("RoomIndex")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartDevice");
                });

            modelBuilder.Entity("HomeAssistant.SmartWasherApi.Models.Domain.SmartWasher", b =>
                {
                    b.HasOne("HomeAssistant.Common.Models.SmartDevice", null)
                        .WithOne()
                        .HasForeignKey("HomeAssistant.SmartWasherApi.Models.Domain.SmartWasher", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeAssistant.Common.Models.SmartDevice", b =>
                {
                    b.Navigation("RoomIndex");
                });
#pragma warning restore 612, 618
        }
    }
}
